### ISSUE TITLE
Problem on call filtering rules: sip URI become all Number

### ISSUE THREAD

**Issue by affanse** [r3gis3r/CSipSimple#51]
@r3gis3r 
CSIPSimple 1.02.03.r2470 armeabi-v7a

Account 1: filter - can't call with starts with: 0/+/*
Account 2: filter - can't call starts with: 0/\* or contains: @
Mobile: filter - can't call contains @

When I try to dial sip URI "sample@sipserver.org" it work nice by using account 1.
The problem arise when "Account 1" sipserver.org not reachable or not active it will rewrite the SIP URI to all number.  It should be just simple exit.

Please take a look at this..
Thank you for your really hardwork.

**Comment by zipcom** [comment]
One would assume that whenever a sip server is not reachable, it will default the called address to be a direct IP call. Am I correct?

The behavior should remain undefined,, when one configures to use SIP server and the SIP server is not available.  Whenever the user is inconsistent, there is no "correct" behavior. Any special application can define its own way.
